# 1.3. Introducing the multidimensional array in NumPy for fast array computations

In [1]:
import random
import numpy as np

In [2]:
n = 1000000
x = [random.random() for _ in range(n)]
y = [random.random() for _ in range(n)]

In [3]:
x[:3], y[:3]

([0.9417614924822254, 0.6046926303972407, 0.5784297124700188],
 [0.21174147212913608, 0.33590993730756, 0.5920539830553494])

In [4]:
z = [x[i] + y[i] for i in range(n)]
z[:3]

[1.1535029646113615, 0.9406025677048008, 1.1704836955253684]

In [5]:
%timeit [x[i] + y[i] for i in range(n)]

94 ms ± 704 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [6]:
xa = np.array(x)
ya = np.array(y)

In [7]:
xa[:3]

array([0.94176149, 0.60469263, 0.57842971])

In [8]:
za = xa + ya
za[:3]

array([1.15350296, 0.94060257, 1.1704837 ])

In [9]:
%timeit xa + ya

436 µs ± 2.18 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [10]:
%timeit sum(x)  # pure Python

4.62 ms ± 25.4 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [11]:
%timeit np.sum(xa)  # NumPy

194 µs ± 1.59 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [12]:
d = [abs(x[i] - y[j])
     for i in range(1000)
     for j in range(1000)]

In [13]:
d[:3]

[0.7300200203530893, 0.6058515551746654, 0.349707509426876]

In [14]:
da = np.abs(xa[:1000, np.newaxis] - ya[:1000])

In [15]:
da

array([[0.73002002, 0.60585156, 0.34970751, ..., 0.46434981, 0.57730545,
        0.17821233],
       [0.39295116, 0.26878269, 0.01263865, ..., 0.12728095, 0.24023659,
        0.15885653],
       [0.36668824, 0.24251978, 0.01362427, ..., 0.10101803, 0.21397367,
        0.18511945],
       ...,
       [0.30685051, 0.18268205, 0.073462  , ..., 0.0411803 , 0.15413594,
        0.24495718],
       [0.05673605, 0.06743241, 0.32357646, ..., 0.20893415, 0.09597851,
        0.49507164],
       [0.32590303, 0.20173457, 0.05440948, ..., 0.06023283, 0.17318847,
        0.22590466]])

In [16]:
%timeit [abs(x[i] - y[j]) \
         for i in range(1000) \
         for j in range(1000)]

122 ms ± 590 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [17]:
%timeit np.abs(xa[:1000, np.newaxis] - ya[:1000])

914 µs ± 6.06 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
